[core]
reloadable = false
order = 0

[package]
version = "2.9.2"
category = "Simulation"
title = "Isaac Sim Kit Helpers"
description = "This Extension that provides a way to launch a python app"
keywords = ["isaac", "kit", "python"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true
toggleable = false

[dependencies]
"omni.usd" = {}

[[python.module]]
name = "isaacsim.simulation_app"
